version: '3.8'

services:
  backend:
    image: ecoeats-backend
    build: ./backend
    environment:
      - PORT=8022
      - URL=${MONGODB_URL}
      - JWT_SECRET=${JWT_SECRET}
    deploy:
      replicas: 2

  frontend:
    image: ecoeats-frontend
    build: ./frontend
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8022
    deploy:
      replicas: 2

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
