export const restaurants = [
  {
    id: 0,
    name: "Restaurant A",
    description: "A fantastic restaurant",
    rating: 4,
    logo: "logo192.png",
    products: [
      {
        id: 0,
        name: "Burger",
        description: "Delicious beef burger with cheese and veggies",
        rating: 4,
        price: 10,
        qte: 0,
        image: "logo192.png",
      },
      {
        id: 2,
        name: "Sushi",
        description: "Assorted sushi rolls with soy sauce and wasabi",
        rating: 4,
        price: 20,
        qte: 0,
        image: "logo192.png",
      },
    ],
  },
  {
    id: 1,
    name: "Restaurant B",
    description: "Delicious food in a cozy atmosphere",
    rating: 5,
    logo: "logo192.png",
    products: [
      {
        id: 1,
        name: "Pizza",
        description: "Classic Margherita pizza with fresh ingredients",
        rating: 5,
        price: 15,
        qte: 0,
        image: "logo192.png",
      },
      {
        id: 3,
        name: "Salad",
        description: "Fresh garden salad with mixed greens and dressing",
        rating: 3,
        price: 12,
        qte: 0,
        image: "logo192.png",
      },
    ],
  },
];
